version: "3"
services:
  postgres:
    image: postgres:11
    ports:
      - 54320:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  api:
    image: node:11
    volumes:
     - ./api:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install && npm run watch"
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - GOOGLE_API_KEY
      - SLACK_OAUTH_TOKEN
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - SLACK_CALLBACK_URL=http://localhost:1234/login
      - DEBUG=true
  app:
    image: node:11
    volumes:
     - ./app:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install && npm run start"
    depends_on:
      - api
    ports:
      - 1234:1234
